Add user authentication
afaraldo/fleet-management-system pull request #17
Opened 2022-10-04 15:41 UTC by KariSanabria

- Install devise gem.
- Add the model, view and user controller.
- Install devise-i18n gem.
- Use template for login.

2022-10-05 02:52 UTC, afaraldo requested changes

2022-10-05 02:52 UTC, afaraldo commented on .rubocop.yml
> +  Enabled: false
Esto no deshabilita globalmente esa metrica? No seria mejor usar exclude y el archivo especifico que causa problemas?

2022-10-05 02:52 UTC, afaraldo commented on app/assets/stylesheets/devise-flash-messages.scss
> +}
Ya boostrap y el template tienen clases css como esta .alert .alert-danger porque tenerlo personalizado. Tampoco encontre donde mismo se usan. Para mi que se puede remover este archivo.

2022-10-05 02:52 UTC, afaraldo commented on app/assets/stylesheets/menu.scss
> +}
Para que estos estilos aparezcan en la aplicación deberian ser importados en el archivo application.bootstrap.scss

Example: @import "print-styles";

Agregar a este archivo y probar. Recuerda ejecutar yarn build:css --watch para ver los cambios.

2022-10-05 02:52 UTC, afaraldo commented on app/controllers/application_controller.rb
> +  # end
Si los comenarios no son necesarios, sacarlos.

2022-10-05 02:52 UTC, afaraldo commented on app/controllers/login_controller.rb
> +end
Borrar este archivo no es necesario, recuerda que la gema device internametne tiene un controllador que es el que se encarga del login.

2022-10-05 02:52 UTC, afaraldo commented on app/helpers/login_helper.rb
> +end
Eliminar este archivo si no tiene métodos

2022-10-05 02:52 UTC, afaraldo commented on app/helpers/users_helper.rb
> +end
Mismo caso que el anterior. Eliminar este archivo si no tiene métodos

2022-10-05 02:52 UTC, afaraldo commented on app/models/user.rb
> +         :trackable
Para mi que por ahora no son necesario los demás módulos. Remover entonces linea 5 al 9

2022-10-05 02:52 UTC, afaraldo commented on app/views/devise/confirmations/new.html.erb
> +<h2>Resend confirmation instructions</h2>
No necesitamos por ahora confirmación. Remover archivo.

2022-10-05 02:52 UTC, afaraldo commented on app/views/devise/mailer/confirmation_instructions.html.erb
> +<p>Welcome <%= @email %>!</p>
mismo caso que el anterior, no se usar aun confirmation.

2022-10-05 02:52 UTC, afaraldo commented on app/views/devise/mailer/email_changed.html.erb
> +<% if @resource.try(:unconfirmed_email?) %>
interesante pero tampoco hace falta que tengamos esto en cuenta ahora. borrar archivo.

2022-10-05 02:52 UTC, afaraldo commented on app/views/devise/mailer/password_change.html.erb
> +
interesante pero tampoco hace falta que tengamos esto en cuenta ahora. borrar archivo.

2022-10-05 02:52 UTC, afaraldo commented on app/views/devise/mailer/reset_password_instructions.html.erb
> +<p>Hello <%= @resource.email %>!</p>
Esto si, lo usaremos. Preferia que este en español ya pero con crear un ticket para no olvidarnos esta bien.

2022-10-05 02:52 UTC, afaraldo commented on app/views/devise/mailer/unlock_instructions.html.erb
> +<p>Hello <%= @resource.email %>!</p>
borrar archivo.

2022-10-05 02:52 UTC, afaraldo commented on app/views/devise/registrations/edit.html.erb
> +<h2>Edit <%= resource_name.to_s.humanize %></h2>
borrar archivo.

2022-10-05 02:52 UTC, afaraldo commented on app/views/devise/registrations/new.html.erb
> +<div class="col-lg-4 mx-lg-auto">
borrar archivo

2022-10-05 02:52 UTC, afaraldo commented on app/views/devise/sessions/new.html.erb
> +<!--      </p>-->
Remover comentarios

2022-10-05 02:52 UTC, afaraldo commented on app/views/devise/sessions/new.html.erb
> +              Recuerdame
Usar I18n.t() para traducciones https://guides.rubyonrails.org/i18n.html

2022-10-05 02:52 UTC, afaraldo commented on app/views/devise/shared/_links.html.erb
> +<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
borrar los innecesarios

2022-10-05 02:52 UTC, afaraldo commented on app/views/devise/unlocks/new.html.erb
> +<h2>Resend unlock instructions</h2>
borrar archivo

2022-10-05 02:52 UTC, afaraldo commented on app/views/layouts/application.html.erb
> -    </div>
mmm... hubiera preferido la otra solucion en la que el layout se selecciona en base al controllador y no esta. Porque mueve todo el codigo a un parcial. No me parece del todo correcto. Pero dejemos asi por ahora.

2022-10-05 02:52 UTC, afaraldo commented on app/views/login/index.html.erb
> +<% if user_signed_in? %>
este archivo no se esta usando creo porque al hacer login te redirige al dashboard. Borrarlo.

2022-10-05 02:52 UTC, afaraldo commented on db/migrate/20220825043114_create_work_orders.rb
> -      t.date :fecha
Esto no es el todo correcto. Las migraciones no se deben modificar directamente. Sino crear nuevas migraciones que corrijan lo anterior. Por ejemplo si cree una tabla y quiero cambiar el nombre de sus columnas como este caso. Crearia otra migracion que llame al metodo [change_column](https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/change_column)

2022-10-05 02:52 UTC, afaraldo commented on db/migrate/20220825043114_create_work_orders.rb
> -      t.date :fecha
Pero dejemoslo asi por ahora.

2022-10-05 02:52 UTC, afaraldo commented on spec/helpers/login_helper_spec.rb
> +require 'rails_helper'
borrar junto con el archivo loginHelper

2022-10-05 02:52 UTC, afaraldo commented on spec/helpers/users_helper_spec.rb
> +require 'rails_helper'
borrrar junto con el archivo users helper

2022-10-05 02:52 UTC, afaraldo commented on spec/models/user_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Agregar validaciones, fijarse en spec/models/car_spec.rb

2022-10-05 02:52 UTC, afaraldo commented on spec/views/login/index.html.erb_spec.rb
> +require 'rails_helper'
borrar esto no se usa. no hay index de login

2022-10-05 02:52 UTC, afaraldo commented on spec/views/users/index.html.erb_spec.rb
> +require 'rails_helper'
por ahroa borrar no hay index de users

2022-10-06 00:16 UTC, KariSanabria commented on app/assets/stylesheets/devise-flash-messages.scss
> +}
En realidad no las utilice luego, era una prueba y me olvide de borrarlo. :)

2022-10-06 00:29 UTC, KariSanabria commented on app/assets/stylesheets/menu.scss
> +}
Funcionó..:)

2022-10-06 00:31 UTC, KariSanabria commented on app/controllers/login_controller.rb
> +end
ok ok! Borro el archivo..

2022-10-06 17:32 UTC, afaraldo approved these changes

2022-10-08 05:55 UTC, afaraldo approved these changes

2022-10-08 06:15 UTC, merged