Abm insurance carrier
afaraldo/fleet-management-system pull request #26
Opened 2022-11-05 22:43 UTC by KariSanabria

Add views
Add controllers
Add models
Fix tests

2022-11-06 23:51 UTC, afaraldo requested changes
Esta correcto falta corregir algunos detalles

2022-11-06 23:51 UTC, afaraldo commented on app/models/insurance_plan.rb
> +  belongs_to :car
Mmm, esto no esta bien del todo. Un auto tiene muchos seguros eso es posible. Y un seguro tiene muchos autos. La relaciones es muchos a muchos. 
1. Usar una relacion [has_and_belongs_to_many](https://guides.rubyonrails.org/association_basics.html#the-has-and-belongs-to-many-association)
2. Falta la relacion del proveedor con el plan de seguro no?

2022-11-06 23:51 UTC, afaraldo commented on app/views/insurance_plans/_form.html.erb
> +                                flatpickr_enable_time: true
no hace falta enable_time, este campo deberia solo de soportar date no datetime. No usar Time.now sino Date.today

2022-11-06 23:51 UTC, afaraldo commented on app/views/insurance_plans/_form.html.erb
> +                                flatpickr_default_date: f.object.exp_date || Time.now,
mismo comentario anterior respecto a fechas

2022-11-06 23:51 UTC, afaraldo commented on app/views/insurance_plans/_form.html.erb
> +          <%= f.association :car, collection: Car.all.page(0),
crear una tarea para selector multiple de autos aqui

2022-11-06 23:51 UTC, afaraldo commented on app/views/insurance_plans/index.html.erb
> +        <%= f.label :amount, for: 'floatingInput' %>
no se va a buscar por presupuesto, quizas por numero pero omitamoslo por ahora.
Agregar proveedor en el buscador.

2022-11-06 23:51 UTC, afaraldo commented on app/views/insurance_plans/index.html.erb
> +          <td><%= insurance_plan.amount %></td>
Falta proveedor

2022-11-06 23:51 UTC, afaraldo commented on db/migrate/20221029002308_create_insurance_plans.rb
> +      t.date :exp_date
agregar index a exp_date
usar nombre completo no abrevidado expiry_date creo que es
falta agregar references to proveedor

2022-11-06 23:51 UTC, afaraldo commented on spec/requests/insurance_plans_spec.rb
> +          skip("Add a hash of attributes valid for your model")
no deberia haber skip en el tests

2022-11-06 23:51 UTC, afaraldo commented on spec/requests/insurance_plans_spec.rb
> +        skip("Add assertions for updated state")
deberia haber un expect en vez de un skip que se espera que haga el test?

2022-11-18 13:26 UTC, afaraldo requested changes

2022-11-18 13:26 UTC, afaraldo commented on app/controllers/insurance_plans_controller.rb
> +  def new
se ve igual a lo que ya hay en ApplicationController y esto ya se esta llamando por defecto ahi. Porque debe ir de nuevo en este controllador.

2022-11-18 13:26 UTC, afaraldo commented on app/models/car.rb
> +  delegate :plate_number, to: :insurance_plans, prefix: true
no se si esto es correcto, recuerda que insurance_plans es un conjunto de planes no uno solo como va tener un conjunto el metodo plate_number

2022-11-18 13:26 UTC, afaraldo commented on app/models/insurance_plan.rb
> +  def full_name
InsurancePlan no tiene que tener full_name eso es para funcionarios o personas

2022-11-18 13:26 UTC, afaraldo commented on app/models/insurance_plan.rb
> +  end
def to_s
   aqui deberia devolverse un numero id o texto con ese dato y usando I18n
end

En realidad deberia tener un numero propio el insurance_plan pero por ahora dejemoslo asi

2022-11-18 13:26 UTC, afaraldo commented on app/models/supplier.rb
> +  delegate :name, to: :insurance_carrier, prefix: true
suplier es el padre
    porque requiere name de los hijos si lo que se instancia son los hijos? Donde se usa esto?

2022-11-18 13:26 UTC, afaraldo commented on config/locales/es.yml
> +      contract_date: Fecha de Contrato
estos creo que ya no son necesarios

2022-11-19 00:02 UTC, KariSanabria commented on app/controllers/insurance_plans_controller.rb
> +  def new
Sip, tienes razón, estuve probando y se quedo eso ahí, pero ya lo borro.

2022-11-23 03:55 UTC, afaraldo approved these changes
Perfect!

2022-11-23 03:55 UTC, merged