Fms 14 roles
afaraldo/fleet-management-system pull request #27
Opened 2022-11-06 00:55 UTC by KariSanabria

Add the 'access granted ~> 1.1.0' gem.
Gem setting.
Generate access_granted:policy.
Defining an access policy.
Checking permissions in views.

2022-12-07 02:28 UTC, afaraldo requested changes

2022-12-07 02:28 UTC, afaraldo commented on app/controllers/suppliers_controller.rb
>  end
Esto debería hacerse en ApplicationController

2022-12-07 02:28 UTC, afaraldo commented on app/policies/access_policy.rb
> +    role :driver do
No debería ser role :driver, { driver?: true }??

2022-12-07 02:28 UTC, afaraldo commented on app/policies/access_policy.rb
> +      can :create, InsurancePlan
1. secretary deberia estar arriba de driver porque tiene mas permisos.
2. usar manage si la secretaria puede crear, editar y borrar ella es la que mas usar el sistema.
3. No debería ser role :secretary, { secretary?: true }??

2022-12-07 02:28 UTC, afaraldo commented on app/views/suppliers/index.html.erb
> +              <%end %>
No, el if can? deberia estar dentro del componente action_buttons. Y ser generico para todos los modelos. El componente posee dos botones editar y borrar. Para editar usar if can? :update y para borrar if can? :destroy

2022-12-07 02:28 UTC, afaraldo commented on app/views/users/index.html.erb
> +          <td><%= add_role(user.role) %></td>
porque dos columnas de roles, si la columna comentada no se usa, eliminar

2022-12-07 02:28 UTC, afaraldo commented on app/helpers/user_helper.rb
> +  def add_role(option_selected)
No debería llamarse add_role, mejor seria show_role_label o algo asi.

2022-12-07 02:28 UTC, afaraldo commented on app/views/work_orders/_form.html.erb
> +                      class: 'btn btn-secondary' if work_order.requested? && work_order.persisted? %>
el if can? :authorize solo debe afectar al boton authorize

2022-12-07 02:28 UTC, afaraldo commented on app/views/work_orders/index.html.erb
> +              <%= render(partial: 'components/action_buttons', locals: { model: work_order })%>
aca se esta esta agregando un espacio y rompe la identacion correcta.

2022-12-07 02:28 UTC, afaraldo commented on config/application.rb
> +    config.autoload_paths += %W[#{config.root}/app/policies #{config.root}/app/roles]
remover #{config.root}/app/roles, esta carpeta no se usa.

2022-12-07 02:28 UTC, afaraldo commented on config/database.yml
> +  # The specified database roles being used to connect to postgres.
esto no deberia haber cambiado

2022-12-07 02:28 UTC, afaraldo commented on config/locales/es.yml
> +        secretary: Secretario/a
Y driver?

2022-12-07 02:28 UTC, afaraldo commented on config/navigation.rb
> +                  if: proc { can? :create, Employee }
debe ser manage

2022-12-07 02:28 UTC, afaraldo commented on config/navigation.rb
> +                  if: proc { can? :create, WorkOrder }
debe ser manager

2022-12-07 02:28 UTC, afaraldo commented on config/navigation.rb
> +                  if: proc { can? :create, Car }
debe ser manager

2022-12-07 18:19 UTC, KariSanabria commented on app/views/suppliers/index.html.erb
> +              <%end %>
Eso te había dicho! pero como cada if can? :update , el_modulo, se debería especificar..
y se tornaría muy extensa y redundante el código. Pero veré una forma mas práctica de hacerlo :)

2022-12-07 18:20 UTC, KariSanabria commented on config/database.yml
> +  # The specified database roles being used to connect to postgres.
No sé porque lo habrá cambiado.

2022-12-08 19:59 UTC, afaraldo approved these changes

2022-12-08 19:59 UTC, afaraldo commented on app/views/components/_action_buttons.html.erb
> +      <% if can? :update, model%>
La indentacion falta corregir deben quedar bien alineado. Tambien separar la palabra model%>  deberia ser 
<% if can? :update, model %>

2022-12-08 20:23 UTC, KariSanabria commented on app/views/components/_action_buttons.html.erb
> +      <% if can? :update, model%>
Sos mas exigente que el rubocop jaja, ni él se quejo jaja

2022-12-09 11:24 UTC, merged